### ISSUE TITLE
Having all of your logging methods be asynchronous results in a LOT of unnecessary object allocations.

### ISSUE THREAD

**Issue by Olian04** [marceloclp/discordial#1]
As you can see below, you currently have all of your logging methods marked as `async`. If you dont know why this is a bad idea, please watch this great talk called [Broken Promises, by James Snell](https://www.youtube.com/watch?v=e3Nh350b6S4).

https://github.com/marceloclp/discordial/blob/634af5ba871fbdd115ea168fafdc5e527fc6feaa/packages/core/logger.ts#L97-L105

**Comment by marceloclp** [comment]
I did not know that. Very good talk as well. I will change them later today :)
